language: ruby

rvm:
  - 2.4.1

cache: bundler

branches:
  only:
  - white # This designates the branch to serve
  - gh-pages

before_install: true

install:
  - gem install bundler
  - bundle install

script:
  - jekyll build && htmlproofer ./_site

# before_cache:
after_success:
  - if [ "$TRAVIS_BRANCH" != "gh-pages" ]; then git checkout -b gh-pages && git push https://$USERNAME:$PASSPHRASE@github.com/commitground/commitground.org.git gh-pages --force
