language: ruby

rvm:
  - 2.4.1

cache: bundler

branches:
  only:
  - white # This designates the branch to serve

before_install: true

install:
  - gem install bundler
  - bundle install

script:
  - jekyll build && htmlproofer ./_site

# before_cache:
after_success:
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - echo -e $SSHKEY >> ~/.ssh/github_rsa
  - chmod 400 ~/.ssh/github_rsa
  - echo "host github.com" >> ~/.ssh/config
  - echo " HostName github.com" >> ~/.ssh/config
  - echo " BatchMode yes" >> ~/.ssh/config
  - echo " IdentityFile ~/.ssh/github_rsa" >> ~/.ssh/config
  - echo " User git" >> ~/.ssh/config
  - git branch -D gh-pages
  - git checkout -b gh-pages
  - git remote add github git@github.com:commitground/commitground.org.git
  - git push github gh-pages --force
